<a href="https://colab.research.google.com/github/itsmeyessir/CCDATSCL_EXERCISES_COM222-ML/blob/main/Exercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 3

<img src="https://img.itch.zone/aW1nLzM0MzUxOTUuanBn/original/FuMxog.jpg" />

In this exercise, you will perform EDA on the popular Pokémon dataset, which contains detailed information about hundreds of Pokémon, including their stats, types, generation, and whether they are legendary.

The Pokémon dataset is ideal for practicing EDA because it includes a mix of numerical features (such as Attack, Defense, Speed, HP) and categorical features (such as Type 1, Type 2, and Generation). This combination allows you to apply a wide range of EDA techniques, including summary statistics, data visualizations, grouping and aggregation, correlation analysis, and comparisons across categories.

Throughout the exercise, you will explore questions such as:
- Which Pokémon tend to have the highest or lowest stats?
- How do different Pokémon types compare in terms of strength or defense?
- Do Legendary Pokémon differ significantly from non-Legendary ones?
- How are various stats distributed across the entire dataset?
- Are there relationships or trade-offs between certain attributes (e.g., Attack vs. Defense)?

In [245]:
import kagglehub
import os
import pandas as pd

In [246]:
# Download latest version
path = kagglehub.dataset_download("abcsds/pokemon")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'pokemon' dataset.
Path to dataset files: /kaggle/input/pokemon

In [247]:
if os.path.isdir(path):
  print(True)

contents = os.listdir(path)
contents

mydataset = path + "/" + contents[0]
mydataset


df = pd.read_csv(mydataset)

True


## 1: Data Understanding (4 pts)

1. Display the first 10 rows.

In [248]:
# put your answer here
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

2. Show dataset shape.

In [249]:
# put your answer here
df.shape

(800, 13)

3. Show all columns and its data types.

In [250]:
# put your answer here
df.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

4. Identify which columns contain missing values.

In [251]:
# put your answer here
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

## 2. Summary Statistics (4 pts)

1. Generate `df.describe()`.

In [252]:
# put your answer here
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

2. Get mean, median, and mode of Attack.

In [253]:
# put your answer here
df['Attack'].mean()

np.float64(79.00125)

In [254]:
df['Attack'].median()

75.0

In [255]:
df['Attack'].mode()

0    100
Name: Attack, dtype: int64

3. Compute 25th and 75th percentiles for HP.

In [256]:
# put your answer here
q25 = df['HP'].quantile(0.25)
q75 = df['HP'].quantile(0.75)

print(f"25th percentile of 'col1': {q25}")
print(f"75th percentile of 'col1': {q75}")

25th percentile of 'col1': 50.0
75th percentile of 'col1': 80.0

In [257]:
df['HP'].quantile([0.25, 0.75])

0.25    50.0
0.75    80.0
Name: HP, dtype: float64

4. Compute standard deviation and variance of Speed.

In [258]:
# put your answer here
df['Speed'].std()

29.06047371716149

## 3. Filtering & Selection `(7 pts)`

Select all Pokémon with Attack > 100.

In [259]:
# put your answer here
df.query('`Attack`> 100')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
39,34,Nidoking,Poison,Ground,505,81,102,77,85,75,85,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Select all Pokémon whose primary type (Type 1) is "Fire".

In [260]:
# put your answer here
df.query('`Type 1` == "Fire"')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,534,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,250,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,410,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,365,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,310,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,405,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,305,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,460,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,470,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,309,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,405,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,316,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,498,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,315,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,484,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,307,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,534,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Select all Pokémon that are Legendary.

In [261]:
# put your answer here
df.query('`Legendary`')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
156,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Select all Pokémon that are Generation 1 AND Legendary.

In [262]:
# put your answer here
df.query('`Generation` == 1 and Legendary')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
156,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True

Select all Pokémon that are Water type OR Grass type.

In [263]:
# put your answer here
df.query('`Type 1` == "Water" or `Type 1` == "Grass" or `Type 2` == "Water" or `Type 2` == "Grass"')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
784,711,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,494,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,494,85,100,122,58,75,54,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Select all Pokémon that are Fire type AND Attack > 120.

In [264]:
# put your answer here
df.query('`Type 1` == "Fire" or `Type 2` == "Fire" and Attack > 120')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,525,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,534,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,250,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,410,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,365,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,310,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,405,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,305,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,460,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,470,70,85,140,85,70,20,3,False
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
435,390,Chimchar,Fire,NaN,309,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,405,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,534,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,540,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,308,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,528,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,316,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,498,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,315,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,484,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,307,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,534,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Select all Pokémon whose type is in this list:
`["Dragon", "Ghost", "Dark"]`.

In [265]:
# put your answer here
df.query('`Type 1` in ["Dragon", "Ghost", "Dark"] or `Type 2` in ["Dragon", "Ghost", "Dark"]')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
99,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False
100,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

## 4. Categorical Exploration `(9 pts)`

Find the number of Pokémon per primary type.

In [266]:
# put your answer here
df['Type 1'].value_counts()

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

Find the number of Pokémon per generation.

In [267]:
# put your answer here
df['Generation'].value_counts()

Generation
1    166
5    165
3    160
4    121
2    106
6     82
Name: count, dtype: int64

Which type appears the most? Which appears the least?

In [268]:
 # put your answer here
import numpy as np

all_types = pd.concat([df['Type 1'], df['Type 2']])

type_counts = all_types.value_counts()

most_frequent_type = type_counts.idxmax()
least_frequent_type = type_counts.idxmin()
most_frequent_count = type_counts.max()
least_frequent_count = type_counts.min()

print("frequency counts for all types:")
print(type_counts)
print(f"\nmost frequent type: {most_frequent_type} (appears {most_frequent_count} times)")
print(f"least frequent type: {least_frequent_type} (appears {least_frequent_count} times)")

frequency counts for all types:
Water       126
Normal      102
Flying      101
Grass        95
Psychic      90
Bug          72
Ground       67
Fire         64
Poison       62
Rock         58
Fighting     53
Dark         51
Dragon       50
Electric     50
Steel        49
Ghost        46
Fairy        40
Ice          38
Name: count, dtype: int64

most frequent type: Water (appears 126 times)
least frequent type: Ice (appears 38 times)

How many unique primary types (Type 1) exist?

In [269]:
 # put your answer here
df['Type 1'].nunique()

18

In [270]:
# for checking only
df['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

How many unique secondary types (Type 2) exist?

In [271]:
 # put your answer here
df['Type 2'].nunique()

18

In [272]:
# for checking only
df['Type 2'].unique()

array(['Poison', nan, 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)


Which primary types have the most dual-type combinations?

In [273]:
 # put your answer here

dual_type_pokemon = df[df['Type 2'].notna()]

unique_combinations_count = dual_type_pokemon.groupby('Type 1')['Type 2'].nunique()

most_combinations = unique_combinations_count.sort_values(ascending=False)

print("primary types by the number of unique dual-type combinations:")
print(most_combinations)

primary types by the number of unique dual-type combinations:
Type 1
Water       14
Rock        12
Bug         11
Electric    10
Grass       10
Fire         9
Ground       9
Dark         8
Steel        8
Dragon       7
Normal       7
Poison       7
Psychic      7
Ghost        6
Ice          5
Fighting     4
Flying       1
Fairy        1
Name: Type 2, dtype: int64

Which type has the highest mean Attack?

In [274]:
# put your answer here
mean_attack_by_type = df.groupby('Type 1')['Attack'].mean()

highest_mean_attack_type = mean_attack_by_type.idxmax()
highest_mean_attack_value = mean_attack_by_type.max()

print(f"the type with the highest mean attack is: {highest_mean_attack_type}")
print(f"mean attack value: {highest_mean_attack_value}")
print("\nmean attack for all types:")
print(mean_attack_by_type.sort_values(ascending=False))

the type with the highest mean attack is: Dragon
mean attack value: 112.125

mean attack for all types:
Type 1
Dragon      112.125000
Fighting     96.777778
Ground       95.750000
Rock         92.863636
Steel        92.703704
Dark         88.387097
Fire         84.769231
Flying       78.750000
Poison       74.678571
Water        74.151786
Ghost        73.781250
Normal       73.469388
Grass        73.214286
Ice          72.750000
Psychic      71.456140
Bug          70.971014
Electric     69.090909
Fairy        61.529412
Name: Attack, dtype: float64

Which type has the lowest mean Defense?

In [275]:
# put your answer here
mean_defense_by_type = df.groupby('Type 1')['Defense'].mean()

lowest_mean_defense_type = mean_defense_by_type.idxmin()
lowest_mean_defense_value = mean_defense_by_type.min()

print(f"the type with the lowest mean defense is: {lowest_mean_defense_type}")
print(f"mean defense value: {lowest_mean_defense_value}")
print("\nmean defense for all types:")
print(mean_defense_by_type.sort_values(ascending=True))

the type with the lowest mean defense is: Normal
mean defense value: 59.8469387755102

mean defense for all types:
Type 1
Normal       59.846939
Fairy        65.705882
Fighting     65.925926
Flying       66.250000
Electric     66.295455
Psychic      67.684211
Fire         67.769231
Poison       68.821429
Dark         70.225806
Bug          70.724638
Grass        70.800000
Ice          71.416667
Water        72.946429
Ghost        81.187500
Ground       84.843750
Dragon       86.375000
Rock        100.795455
Steel       126.370370
Name: Defense, dtype: float64


Which generation has the highest average Speed?

In [276]:
# put your answer here
mean_speed_by_gen = df.groupby('Generation')['Speed'].mean()

highest_mean_speed_gen = mean_speed_by_gen.idxmax()
highest_mean_speed_value = mean_speed_by_gen.max()

print(f"the generation with the highest mean speed is: {highest_mean_speed_gen}")
print(f"mean speed value: {highest_mean_speed_value}")
print("\nmean speed for all generation:")
print(mean_speed_by_gen.sort_values(ascending=False))

the generation with the highest mean speed is: 1
mean speed value: 72.58433734939759

mean speed for all generation:
Generation
1    72.584337
4    71.338843
5    68.078788
3    66.925000
6    66.439024
2    61.811321
Name: Speed, dtype: float64

## 5. Groupby & Aggregation `(13 pts)`

Compute the average Attack per primary type.

In [277]:
# put your answer here
df.groupby('Type 1')['Attack'].mean()

Type 1
Bug          70.971014
Dark         88.387097
Dragon      112.125000
Electric     69.090909
Fairy        61.529412
Fighting     96.777778
Fire         84.769231
Flying       78.750000
Ghost        73.781250
Grass        73.214286
Ground       95.750000
Ice          72.750000
Normal       73.469388
Poison       74.678571
Psychic      71.456140
Rock         92.863636
Steel        92.703704
Water        74.151786
Name: Attack, dtype: float64

Compute the maximum HP per generation.

In [278]:
# put your answer here
df.groupby('Generation')['HP'].max()

Generation
1    250
2    255
3    170
4    150
5    165
6    126
Name: HP, dtype: int64

Compute the total number of Pokémon per primary type.

In [279]:
# put your answer here
df.groupby('Type 1')['Total'].value_counts()

Type 1  Total
Bug     500      5
        205      4
        424      4
        600      4
        195      3
                ..
Water   635      1
        640      1
        670      1
        680      1
        770      1
Name: count, Length: 550, dtype: int64

For each type, compute:

- mean Attack

- mean Defense

- mean Speed

In [280]:
# put your answer here
df.groupby('Type 1')[['Attack', 'Defense', 'Speed']].mean()

              Attack     Defense       Speed
Type 1
Bug        70.971014   70.724638   61.681159
Dark       88.387097   70.225806   76.161290
Dragon    112.125000   86.375000   83.031250
Electric   69.090909   66.295455   84.500000
Fairy      61.529412   65.705882   48.588235
Fighting   96.777778   65.925926   66.074074
Fire       84.769231   67.769231   74.442308
Flying     78.750000   66.250000  102.500000
Ghost      73.781250   81.187500   64.343750
Grass      73.214286   70.800000   61.928571
Ground     95.750000   84.843750   63.906250
Ice        72.750000   71.416667   63.458333
Normal     73.469388   59.846939   71.551020
Poison     74.678571   68.821429   63.571429
Psychic    71.456140   67.684211   81.491228
Rock       92.863636  100.795455   55.909091
Steel      92.703704  126.370370   55.259259
Water      74.151786   72.946429   65.964286

For each generation, compute:

- count

- mean Total

- number of Legendary Pokémon (hint: use sum on Boolean)

In [281]:
# put your answer here
df.groupby('Generation').agg(count=('Name', 'size'), mean_Total=('Total', 'mean'), num_Legendary=('Legendary', 'sum')).reset_index()

   Generation  count  mean_Total  num_Legendary
0           1    166  426.813253              6
1           2    106  418.283019              5
2           3    160  436.225000             18
3           4    121  459.016529             13
4           5    165  434.987879             15
5           6     82  436.378049              8

Which type combination (Type 1 + Type 2) has the highest average Attack?

In [282]:
# put your answer here
df.groupby(['Type 1', 'Type 2'])['Attack'].mean().sort_values(ascending=False)

Type 1   Type 2
Ground   Fire        180.000000
Psychic  Fighting    160.000000
         Dark        160.000000
Bug      Fighting    155.000000
Dragon   Electric    150.000000
                        ...
Normal   Fairy        45.000000
Ghost    Fire         41.666667
Ice      Psychic      40.000000
Water    Fairy        35.000000
Bug      Water        30.000000
Name: Attack, Length: 136, dtype: float64

Which generation has the highest proportion of Legendary Pokémon?

In [283]:
# put your answer here
df.groupby(['Generation'])['Legendary'].mean().sort_values(ascending=False)

Generation
3    0.112500
4    0.107438
6    0.097561
5    0.090909
2    0.047170
1    0.036145
Name: Legendary, dtype: float64


Which primary type has the largest variance in HP?

In [284]:
# put your answer here
df.groupby('Type 1')['HP'].var().sort_values(ascending=False)

Type 1
Normal      1312.861456
Ghost       1003.995968
Psychic      807.772556
Water        755.536599
Fighting     668.361823
Ground       658.563508
Dragon       566.221774
Fairy        556.360294
Ice          453.130435
Dark         444.294624
Rock         434.050740
Flying       428.250000
Poison       386.712963
Grass        380.896273
Fire         376.519985
Electric     299.515328
Bug          266.633419
Steel        257.410256
Name: HP, dtype: float64

Which primary type has the highest median Speed?

In [285]:
# put your answer here
df.groupby('Type 1')['Speed'].median().sort_values(ascending=False)

Type 1
Flying      116.0
Dragon       90.0
Electric     88.0
Psychic      80.0
Fire         78.5
Normal       71.0
Dark         70.0
Ground       65.0
Water        65.0
Poison       62.5
Ice          62.0
Ghost        60.5
Bug          60.0
Fighting     60.0
Grass        58.5
Rock         50.0
Steel        50.0
Fairy        45.0
Name: Speed, dtype: float64

Group Pokémon by whether they are Legendary or not. Compare:

- mean Total

- mean Attack

- mean Defense

- mean Speed

In [286]:
# put your answer here
df.groupby('Legendary')[['Total', 'Attack', 'Defense', 'Speed']].mean()

                Total      Attack    Defense       Speed
Legendary
False      417.213605   75.669388  71.559184   65.455782
True       637.384615  116.676923  99.661538  100.184615

Show the top 5 strongest types by mean Total.

In [287]:
# put your answer here
df.groupby('Type 1')['Total'].mean().sort_values(ascending=False).head(5)

Type 1
Dragon     550.531250
Steel      487.703704
Flying     485.000000
Psychic    475.947368
Fire       458.076923
Name: Total, dtype: float64

Rank generations by their average Attack.

In [288]:
# put your answer here
df.groupby('Generation')['Attack'].mean().rank(ascending=False).sort_values(ascending=False)

Generation
2    6.0
6    5.0
1    4.0
3    3.0
5    2.0
4    1.0
Name: Attack, dtype: float64

Show the top 10 fastest Pokémon using nlargest(10, "Speed").

In [289]:
# put your answer here
df.nlargest(10, "Speed")

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
431,386,DeoxysSpeed Forme,Psychic,NaN,600,50,95,90,95,90,180,3,True
315,291,Ninjask,Bug,Flying,456,61,90,45,50,50,160,3,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
109,101,Electrode,Electric,NaN,480,60,50,70,80,80,140,1,False